### ISSUE TITLE
[BUG] Exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND

### ISSUE THREAD

**Issue by wroyca** [gtk-rs/gtk4-rs#1130]
## Bug description

GTK4-RS ([MSVC toolchain](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#msvc-toolchain)) is unable to run under Windows 11:

```bash
error: process didn't exit successfully: `target\debug\basics.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

[Code sample as small as possible which reproduces the bug.
](https://github.com/gtk-rs/gtk4-rs/tree/master/examples/basics)

## Backtrace

Can't be produced as it doesn't run. However, there's an available PDB: [basics.zip](https://github.com/gtk-rs/gtk4-rs/files/9668176/basics.zip)

## Note

Both GTK4 and Libadwaita are properly built on my system with all their dependencies; I can run their individual demos.

**Comment by Valhrafnaz** [comment]
I was having the same issue. Using the same steps provided [here] 
(https://gist.github.com/Ep0chalypse/0e0f9ef43eb7f0218eaa8fe0822f3d36), I found that my .exe was trying to load harfbuzz.dll from AdoptOpenJDK, so I just uninstalled that since I don't need it anymore. Alternatively, you could move the C:\gnome\bin higher in the PATH environment variable, so that it has precedence over whatever location the (I assume outdated) dll is located.

**Comment by wroyca** [comment]
> I was having the same issue. Using the same steps provided [here] (https://gist.github.com/Ep0chalypse/0e0f9ef43eb7f0218eaa8fe0822f3d36), I found that my .exe was trying to load harfbuzz.dll from AdoptOpenJDK, so I just uninstalled that since I don't need it anymore. Alternatively, you could move the C:\gnome\bin higher in the PATH environment variable, so that it has precedence over whatever location the (I assume outdated) dll is located.

Impressive timing. I was just about to say **exactly** that. 🤯 
In my case, it was:
![image](https://user-images.githubusercontent.com/91024200/192893155-56fcfd48-82af-4b3a-b17d-600ef03e3922.png)
