### ISSUE TITLE
book: Add mention of hiding windows command console and build commands

### ISSUE THREAD

**Issue by JPLost** [gtk-rs/gtk4-rs#1177]
I would recommend mentioning hiding of windows command console on the tutorial
#![windows_subsystem = "windows"]

And can you build a smaller executable file for the tutorials or does it pack all the gtk4 features?

**Comment by bilelmoussaoui** [comment]
For the first part, we already have an issue for it https://github.com/gtk-rs/gtk4-rs/issues/848

not sure what do you mean by creating a small executable for the tutorials? The intention of the book/examples is to have some "code" you can read and copy paste to modify based on your needs instead of some demo.

**Comment by Hofer-Julian** [comment]
> I would recommend mentioning hiding of windows command console on the tutorial
#![windows_subsystem = "windows"]

I would be fine with that in the examples, but not adding it to every snippet in the book.
The only thing we could do is mention that briefly in one of the chapters.

**Comment by JPLost** [comment]
Mentioning it in one of the chapters is fine. The file size is not so much of an issue, but more of a question in this case.

**Comment by bilelmoussaoui** [comment]
I am going to close this one, as we already have #848 to track a proper chapter about distributing a windows app.
