### ISSUE TITLE
Compilation issue with libadwaita main branch due to AboutWindow breaking change

### ISSUE THREAD

**Issue by wroyca** [gtk-rs/gtk4-rs#1355]
Hey there! 

So in the stable version of the book, we recommend that users build libadwaita from the main branch. However, we ran into a bit of a hiccup due to a recent breaking change in AboutWindow, which prevent us from being able to compile Libadwaita on Windows as it introduced appstream as a hard-dependency. 

To get around this, we should suggest that users clone libadwaita-1-3 for now, although I should note that it's only a matter of time before we'll need to transition to version 1.4 where the breaking change lies.

For more information, you may want to check out the relevant discussions over at:
https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/833 and https://github.com/ximion/appstream/issues/231

cc @Exalm

**Comment by bilelmoussaoui** [comment]
The only issue to be solved here is to make the book use the latest stable release. Anything else should be resolved upstream.

**Comment by Exalm** [comment]
I mean I'll just reiterate what I said in the libadwaita MR. AppStream issue has had the help wanted tag for more than 3 years now and ximion mentioned they would be fine with a port, just worried there would be no users. Libadwaita would be that user.

If nobody wants to do that - I mean then 1.4 is gonna be released as is. Because just as in the appstream issue, libadwaita does not explicitly target Windows - if it works, cool, but it's not a requirement and nobody working on libadwaita is testing it there.
