### ISSUE TITLE
Remove all the `Option<Box<dyn Fn()>>>` usages

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#294]
There are a few callbacks that are still optional. We should investigate whether those makes sense to be optional or not, if it's the case split the function into a `set_callback_name` & `unset_callback_name`

**Comment by bilelmoussaoui** [comment]
see #28 for an example

**Comment by sophie-h** [comment]
Is there something special that makes is especially annoying for closures? (cc @sdroege)

Otherwise I would suggest to only do this change via gir. Otherwise thinks will get inconsistent because there is a lot of setters that accept an option, but you usually don't need it. Examples

- `GtkWindowExt::set_title`: "Passing None does the same as setting the title to an empty string." Super useless. But still nice to have a semantically called "unset" function for them.
- `HdyPreferencesRow::set_title`: Some of those actually only stop reserving space for the text if set to NULL. Still, usually you just want to set a text.

Does the Rust rules for getters/setters contain something like unset?

**Comment by bilelmoussaoui** [comment]
I'm not very sure what you mean by doing this change through gir? as in add an option for handling callbacks in case they can be nullable?

**Comment by sophie-h** [comment]
No, splitting all setters that accept an `Option` into `set_` and `unset_`. Or don't do it at all.

**Comment by sophie-h** [comment]
Since others are doing huge work on getting rid of the `get_` from the names to conform to https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis, maybe there should be some discussion before adding a new naming convention that is not part the rust naming convention.

**Comment by bilelmoussaoui** [comment]
Sure, it has been what gtk-rs doing for a while.  If you look at Listbox::bind_model for example. There are very few use cases, probably less than 10 ones to handle manually in the whole gtk4-rs repository that doing that work manually seems fine to me. 

Writing Some(Box::new(callback)) is just ugly and makes the code way less readable if combined with the clone macro.

**Comment by sdroege** [comment]
In GStreamer it was 3 places where this pattern appeared, so I also didn't consider making this a generic gir feature. `set` / `unset` feels much nicer during usage in any case.
