### ISSUE TITLE
DrawingArea draw func should be FnMut instead of Fn

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#548]
It seems that the only way to draw on a DrawingArea is to set a callback using `DrawingAreaExt::set_draw_func()`. But then the problem is that you can't pass any data to the drawing function. The original C interface at least has a gpointer to pass data to the function but gtk4-rs just uses this function signature `Fn(&DrawingArea, &Context, i32, i32)`. Of course you could capture the data in a closure but that'd need to be immutable or cloned which is not very convenient. Or you could probably define your own GObject just for storing information, but that doesn't sound like a good idea if you want to process the data from "normal" Rust code as well.

Maybe I've overlooked some details and there's actually an alternative solution to draw on a DrawingArea. Technically GLArea does have a `GLAreaExt::context()` method to receive the context and I wonder why this isn't available for DrawingArea as well.

**Comment by sdroege** [comment]
You pass the data into the closure by capturing the variables somehow, just like with signal handlers and other callbacks

```rust
let x = your_stuff;
area.set_draw_func(move |...| {
    // do things with x
});
```

**Comment by AaronErhardt** [comment]
Yeah, I know...

> Of course you could capture the data in a closure but that'd need to be immutable or cloned which is not very convenient

**Comment by sdroege** [comment]
I think the draw func here could be `FnMut()`, which would solve part of your problem. If you want to send a PR for that, please go ahead. (CC @bilelmoussaoui ). Let's re-purpose this issue for that.

That's however not the case for signal handlers and there you'd have to make use of interior mutability, or otherwise if they were `FnMut()` it would be unsound.

**Comment by AaronErhardt** [comment]
I don't know whether FnMut helps me here. Anyway, I spent the whole day trying to get my code to work and in the end I just realized that - unless I missed some details - GTK has nothing comparable to what I want. Just something similar to a canvas in JavaScript. There's nothing you can simply draw on without a callback.

Yet eventually I had a look at relm which implemented this DrawHandler hack for gtk3-rs: [the hack](https://github.com/antoyo/relm/blob/master/src/drawing.rs) + [example application](https://github.com/antoyo/relm/blob/master/relm-examples/examples/drawing.rs)

I didn't want to use it at first because I thought there must have been something built into GTK to properly implement this but after suffering for hours without success I guess that's the only available solution.

So in the end, I just ported it to gtk4-rs: [the hack](https://github.com/AaronErhardt/relm4/tree/drawing/src) + [example application](https://github.com/AaronErhardt/relm4/blob/drawing/relm4-examples/examples/drawing.rs)

This means from my side this issue can be closed although I'm not really happy with the solution.

Regardless I really appreciate your feedback and that you took your time to have a look at this issue :)

**Comment by sdroege** [comment]
> I don't know whether FnMut helps me here.

Well, you could have a mutable state in the callback that you then can change on every call. Is that not sufficient?

> There's nothing you can simply draw on without a callback.

From where should the drawing happen otherwise? You could always draw to a cairo image surface from wherever you want and then blit it over the drawing area, which is basically what you're doing right now.

> which implemented this DrawHandler hack

That's not really a hack but also a valid approach for drawing on the drawing area.

**Comment by AaronErhardt** [comment]
As far as I understand FnMut would allow me to capture data in the closure once and then edit it from the closure. That'd definitely would be better than the current version but isn't exactly what I need. I want to edit the data from outside. Or even better, never even need to capture data in the closure because I can draw from outside. Especially in the case of relm and even more for Relm4 this is necessary because data and widgets are kept separately. Therefor passing data to the draw closure would only work with an immutable reference which I can't capture.

**Comment by sdroege** [comment]
In that case you really want double buffering like you have now. You'd have a surface that you fill from the outside somewhere, whenever it changes you tell the drawing area that a redraw is needed, and from the drawing area's draw function (which could also be called at other times to refresh the content btw) you would render the latest surface that is available.

Rendering into the drawing area from a callback has to happen because redrawing might also be needed based on external events like window resizing, for example.

In any case, it should be converted to a `FnMut` as that makes other setups than yours easier. But for your setup, what you're doing right now is correct approach.
