### ISSUE TITLE
[FEATURE REQUEST] Book: clarify code snippets by referencing proper setup of the provided code, but containing it on another page

### ISSUE THREAD

**Issue by ahhhh6980** [gtk-rs/gtk4-rs#967]
One problem though, the listing for the to-do app does not compile
![unknown](https://user-images.githubusercontent.com/49384256/157546773-07535f04-9dd0-4d19-a540-838da5677cfb.png)

second, I find it would be beneficial to go into more depth about how to structure the folders for a widget, and going into the steps for implementing the `impl.rs` and `mod.rs` files, and why they are two separate files.

Probably by not starting out with a complete implementation, but starting with how to structure the folder/files, then starting with a blank overview of the layout and requirements of the `impl`, `mod` and `.ui` files, then going into more specifics of the general things you would have to program to get these working, until eventually the code examples are filled, with an entire implementation of a widget.

Since its a lot of information (at least to me, likely to others), just easing into it into like, idk, maybe a 4 segment chapter, would probably make it a lot easier to understand.

I apologize if this is not well formatted, I believe this is my first time posting an issue to anything on github. I look forward to learning more about gtk-rs and hope to be able to contribute to its documentation in the future if I can get past understanding it :)

**Comment by Hofer-Julian** [comment]
> One problem though, the listing for the to-do app does not compile

It surely does, because it passes our CI.
One thing I see, that you use `klass.bind_template` which only works if you use the crate directly from git.
The rest I assume you've simply copy-pasted only parts of the code, but hard to guess without seeing the whole code.

> second, I find it would be beneficial to go into more depth about how to structure the folders for a widget

I see that Rust modules can be confusing, but that's not really specific to gtk-rs.
Maybe you find this post helpful?
https://fasterthanli.me/articles/rust-modules-vs-files
